export { default as ErrorPage } from './Error/ErrorPage'
export { default as LoginPage } from './Authentication/LoginPage'
export { default as SignUpPage } from './Authentication/SignUpPage'
export { default as AuthenticationPage } from './Authentication/AuthenticationPage'
export { default as VerifyEmail } from './Verify/VerifyEmail'
